language: nodeCreate public and private SSH keysjs
nodejs:
  - 6.9.1
notifications:
  email:
    onfailure: change
    onsuccess: change
addons:
  sshknownhosts:
    - SERVER_IP
branches:
  only:
    - master
env:
  global:
    - REMOTEAPPDIR=/var/www/MYDOMAIN.COM/
    - REMOTEUSER=deploy
    - REMOTEHOST=SERVER_IP
    - PORT=8080
beforeinstall:
  - npm install -g npm@^2
install:
  - npm install --only=dev
beforescript:
  - chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
  - npm run build
after_success:
  - "./scripts/deploy.sh"
before_install:
  - openssl aes-256-cbc -K $encrypted_73d4c2b5bdee_key -iv $encrypted_73d4c2b5bdee_iv
    -in deploy.enc -out deploy -d
