version: "3"

services:

#######################
#  Backend container  #
#######################
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    expose:
      - 8000
    environment:
      BACKEND_HOST: "localhost:8000"
      BACKEND_PORT: "8000"
    ports:
      - 8000:8000
    links:
      - mongo
    volumes:
      - ./backend/src:/srv/app/backend/src
    command: npm start

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"


########################
#  Frontend container  #
########################

  frontend:
    build: ./frontend
    expose:
      - 80
    environment:
      - FRONTEND_PORT:80
    ports:
      - 80:80
    volumes:
      - ./frontend/src:/srv/app/frontend/src
      - ./frontend/build:/srv/app/frontend/build
      - ./frontend/public:/srv/app/frontend/public
    links:
      - backend
    command: [nginx, '-g', 'daemon off;']
